version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: social-network
    container_name: social-network-container
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    
 